#!/bin/bash
set -uo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DIR/lib.sh"

MD=/etc/claude-code/CLAUDE.md

echo "Container instruction tests"
echo "==========================="

# run.sh starts testing as soon as init-proxy.sh touches /tmp/.proxy-ready, which
# happens moments before the entrypoint regenerates CLAUDE.md.
for _ in $(seq 1 20); do
    grep -q "Generated by write-container-md" "$MD" 2>/dev/null && break
    sleep 0.5
done

assert_pass "managed CLAUDE.md exists" \
    test -f "$MD"

assert_pass "owned by root and read-only" \
    sh -c "[ \"\$(stat -c '%U %a' $MD)\" = 'root 444' ]"

# The entrypoint regenerated the file rather than leaving the build-time seed:
# only write-container-md emits this header.
assert_pass "regenerated at startup" \
    grep -q "Generated by write-container-md" "$MD"

assert_pass "carries apt-safe guidance" \
    grep -q "sudo apt-safe install" "$MD"

assert_pass "carries the firewall network section" \
    grep -q "restricted by a Squid proxy" "$MD"

# Domains passed via CLAUDE_DOCKER_ALLOW_DOMAINS are appended to the squid
# allowlist at startup, so finding one proves the allowlist was read at runtime.
assert_pass "carries the live proxy allowlist" \
    grep -q "^- .google.com$" "$MD"

assert_fail "agent cannot rewrite it" \
    sh -c "echo x >> $MD"

assert_fail "agent cannot write the instruction source" \
    sh -c "echo x >> /etc/claude-code/container.md"

test_summary
